project_name: sysl
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod tidy

build:
  binary: sysl
  id: sysl
  main: ./cmd/sysl
  ldflags:
    - -s -w -X main.Version={{.Version}}
    - -X main.GitCommit={{.ShortCommit}}
    - -X main.BuildDate={{.Date}}
    - -X main.BuildOS={{.Os}}/{{.Arch}}
    # - -s -w -X "main.GoVersion={{.Env.GOVERSION}}"
  goos:
    - windows
  goarch:
    - amd64
  goarm:
    - 7

archives:
- id: "sysl"
  builds: ['sysl']
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    windows: windows
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
    - README.md
    - LICENSE

snapshot:
checksum:
  name_template: '{{.ProjectName}}_{{.Version}}_checksums.txt'