swagger: "2.0"
basePath: /api/v1

host: goat.example.com

info:
  title: Goat CRUD API
  version: 1.2.3

paths:
  /goat/status:
    get:
      description: Get goat status
      produces:
        - application/json
      responses:
        '200':
          description: 'okay'
      summary: Get goat status
