
swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /users/{id}:
    get:
      summary: Gets a user by ID.
      parameters:
        - in: query
          name: metadata
          type: boolean
          required: false
          description: If true, the endpoint returns only the user metadata.
        - $ref: '#/parameters/id'
        - $ref: '#/parameters/Request-id'
      responses:
        '200':
          description: OK
parameters:
  id:
    in: path
    name: id
    type: integer
    required: true
    description: The user ID.
  Request-id:
    in: header
    name: request-id
    type: string
    required: true
    description: the request ID.
