swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /users/{id}:
    parameters:
      - $ref: '#/parameters/id'
      - in: header
        name: metadata
        type: boolean
        required: false
    get:
      summary: Gets a user by ID
      responses:
        '200':
          description: OK
parameters:
  id:
    in: path
    name: id
    type: integer
    required: true
    description: The user ID.
