swagger: "2.0"
info:
  title: Simple
paths: {}

definitions:
  Goat:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
      weight:
        type: number
