swagger: "2.0"
basePath: /fruit-basket
info:
  title: Fruit API
  version: 1.0.0
definitions:
  SimpleObj:
    type: object
    properties:
      date:
        type: string
      string:
        type: string
paths: {}
